import React, { createContext, useContext, useState } from 'react';

export type LanguageCode = 'uz' | 'ru' | 'en';

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const translations: Record<LanguageCode, Record<string, string>> = {
  uz: {
    // Navigation
    nav_home: "Asosiy",
    nav_restaurants: "Restoranlar",
    nav_settings: "Sozlamalar",

    // Dashboard
    dash_title: "Boshqaruv paneli",
    dash_sub: "EcoRestaurant platformasi monitoringi",
    dash_balance: "Balans",
    dash_my_account: "Mening Hisobim",
    dash_top_up_btn: "Hisobni to'ldirish",
    dash_withdrawable: "Yechib olinadigan pul",
    dash_withdraw_btn: "Chiqarib olish",
    dash_active_orders: "Faol buyurtmalar",
    dash_received_orders: "Olingan buyurtmalar",
    dash_total_revenue: "Jami tushum",
    dash_sum: "so'm",
    dash_recent_orders: "Oxirgi buyurtmalar",
    dash_new_order: "Yangi buyurtma keldi!",
    dash_customer: "Mijoz",
    dash_total: "Jami",
    dash_status: "Holat",
    dash_loading: "Yuklanmoqda...",
    dash_today: "Bugun",
    dash_preparing: "Hozir tayyorlanmoqda",
    dash_avg_check: "O'rtacha chek",
    dash_control: "Boshqaruv",
    dash_stats: "Statistika",
    dash_add_menu: "Menyu qo'shish",

    // Restaurants
    rest_title: "Mening Restoranlarim",
    rest_sub: "Ulangan botlar va restoranlar ro'yxati",
    rest_add_btn: "Yangi Restoran",
    rest_modal_title: "Token orqali bot ulash",
    rest_modal_name: "Restoran nomi",
    rest_modal_token: "Bot tokeni",
    rest_modal_create: "Yaratish",
    rest_modal_cancel: "Bekor qilish",
    rest_active: "Faol",
    rest_inactive: "Nofaol",
    rest_delivery: "Yetkazib berish",
    rest_min_order: "Minimal zakaz",
    rest_manage_btn: "Boshqarish",
    rest_count_suffix: "ta restoran",
    rest_empty_title: "Sizda hali restoranlar yo'q",
    rest_empty_btn: "Birinchi restoranni qo'shish",
    rest_online: "Online",
    rest_delete_warn: "Xavfsizlik yuzasidan restoranni o'chirish faqat tizim administratori orqali amalga oshiriladi.",
    rest_orders_today: "ta buyurtma bugun",
    rest_success_add: "Restoran muvaffaqiyatli qo'shildi!",
    rest_error_add: "Xatolik yuz berdi. Bot tokenini tekshiring.",
    rest_modal_desc: "Bot va restoran ma'lumotlarini kiriting",
    rest_modal_tip: "* Har bir restoran uchun alohida bot tavsiya etiladi",
    rest_save_connect: "Saqlash va Ulanish",
    rest_manage: "Boshqarish",

    // Settings
    settings_title: "Sozlamalar",
    settings_sub: "Hisobingiz va to'lov sozlamalarini boshqaring",
    settings_profile_title: "Profil & To'lov ma'lumotlari",
    settings_owner_name: "Foydalanuvchi ismi",
    settings_phone: "Telefon raqami",
    settings_card: "Pul tushadigan karta raqami (Buyurtmalar uchun)",
    settings_card_tip: "* Mijoz buyurtma berganida ushbu kartaga pul o'tkazish tavsiya etiladi",
    settings_save_btn: "Saqlash",
    settings_saving: "Saqlanmoqda...",
    settings_language_title: "Til sozlamalari",
    settings_help_center: "Yordam markazi",
    settings_help_sub: "FAQ va texnik qo'llab-quvvatlash",
    settings_notifications: "Bildirishnomalar",
    settings_notif_sub: "Push va tovush sozlamalari",
    settings_logout: "Chiqish",
    settings_card_holder: "Karta Egasi",
    settings_card_phone: "Telefon",
    settings_save_success: "Profil ma'lumotlaringiz muvaffaqiyatli saqlandi!",
    settings_save_error: "Saqlashda xatolik yuz berdi.",
    settings_notif_alert: "Tez orada faollashtiriladi.",
    settings_logout_alert: "Hisobdan chiqildi.",

    // Manage Restaurant
    tab_orders: "Buyurtmalar",
    tab_categories: "Kategoriyalar",
    tab_items: "Taomlar",
    tab_settings: "Sozlamalar",
    orders_active_only: "Faol buyurtmalar",
    orders_all: "Barcha buyurtmalar",
    orders_address: "Yetkazib berish manzili",
    orders_phone: "Telefon",
    orders_payment: "To'lov turi",
    orders_items: "Zakaz tarkibi",
    orders_update_status: "Holatni yangilash",
    cats_title: "Kategoriyalar ro'yxati",
    cats_new: "Yangi kategoriya",
    cats_add_btn: "Qo'shish",
    cats_name_placeholder: "Masalan: Pitsalar",
    items_title: "Taomlar ro'yxati",
    items_new: "Yangi Taom",
    items_edit: "Taomni Tahrirlash",
    items_name: "Taom nomi",
    items_desc: "Tavsif (Description)",
    items_price: "Narxi (so'm)",
    items_cat: "Kategoriya",
    items_image: "Rasm havolasi (Image URL)",
    items_upload_btn: "Rasm yuklash",
    items_available: "Hozir sotuvda bormi?",
    items_saving: "Saqlanmoqda...",
    items_cancel: "Bekor qilish",
    items_no_cat_warn: "Taom qo'shish uchun avval kategoriya yaratishingiz kerak. Taomlar faqat kategoriya ichida ko'rinadi.",
    items_go_cat_btn: "Kategoriya yaratishga o'tish",
    rest_settings_title: "Restoran sozlamalari",
    rest_name: "Restoran nomi",
    rest_address: "Manzil",
    rest_delivery_fee: "Yetkazib berish narxi (so'm)",
    rest_min_order_form: "Minimal buyurtma narxi (so'm)",
    rest_working_start: "Ish boshlanishi",
    rest_working_end: "Ish tugashi",
    rest_is_active: "Restoran faolmi?",
    rest_branding_title: "Brending Sozlamalari",
    rest_logo_url: "Logo Havolasi (Logo URL)",
    rest_logo_upload: "Logo yuklash",
    rest_theme: "Ilova Mavzusi (Theme)",
    rest_accent: "Asosiy Rang (Branding Accent)"
  },
  ru: {
    // Navigation
    nav_home: "Главная",
    nav_restaurants: "Рестораны",
    nav_settings: "Настройки",

    // Dashboard
    dash_title: "Панель управления",
    dash_sub: "Мониторинг платформы EcoRestaurant",
    dash_balance: "Баланс",
    dash_my_account: "Мой счет",
    dash_top_up_btn: "Пополнить баланс",
    dash_withdrawable: "Доступно к выводу",
    dash_withdraw_btn: "Вывести средства",
    dash_active_orders: "Активные заказы",
    dash_received_orders: "Получено заказов",
    dash_total_revenue: "Общая выручка",
    dash_sum: "сум",
    dash_recent_orders: "Последние заказы",
    dash_new_order: "Пришел новый заказ!",
    dash_customer: "Клиент",
    dash_total: "Итого",
    dash_status: "Статус",
    dash_loading: "Загрузка...",
    dash_today: "Сегодня",
    dash_preparing: "Готовится",
    dash_avg_check: "Средний чек",
    dash_control: "Управление",
    dash_stats: "Статистика",
    dash_add_menu: "Добавить в меню",

    // Restaurants
    rest_title: "Мои Рестораны",
    rest_sub: "Список подключенных ботов и ресторанов",
    rest_add_btn: "Новый Ресторан",
    rest_modal_title: "Подключение бота через токен",
    rest_modal_name: "Название ресторана",
    rest_modal_token: "Токен бота",
    rest_modal_create: "Создать",
    rest_modal_cancel: "Отмена",
    rest_active: "Активен",
    rest_inactive: "Неактивен",
    rest_delivery: "Доставка",
    rest_min_order: "Мин. заказ",
    rest_manage_btn: "Управлять",
    rest_count_suffix: "ресторанов",
    rest_empty_title: "У вас еще нет ресторанов",
    rest_empty_btn: "Добавить первый ресторан",
    rest_online: "Онлайн",
    rest_delete_warn: "В целях безопасности удаление ресторана возможно только через системного администратора.",
    rest_orders_today: "заказов сегодня",
    rest_success_add: "Ресторан успешно добавлен!",
    rest_error_add: "Произошла ошибка. Проверьте токен бота.",
    rest_modal_desc: "Введите данные бота и ресторана",
    rest_modal_tip: "* Для каждого ресторана рекомендуется отдельный бот",
    rest_save_connect: "Сохранить и подключить",
    rest_manage: "Управлять",

    // Settings
    settings_title: "Настройки",
    settings_sub: "Управление аккаунтом и платежами",
    settings_profile_title: "Профиль и реквизиты",
    settings_owner_name: "Имя пользователя",
    settings_phone: "Номер телефона",
    settings_card: "Номер карты для вывода (для заказов)",
    settings_card_tip: "* Рекомендуется использовать эту карту для перевода при заказе клиентов",
    settings_save_btn: "Сохранить",
    settings_saving: "Сохранение...",
    settings_language_title: "Языковые настройки",
    settings_help_center: "Центр поддержки",
    settings_help_sub: "FAQ и техподдержка",
    settings_notifications: "Уведомления",
    settings_notif_sub: "Настройки пуш и звука",
    settings_logout: "Выйти",
    settings_card_holder: "Владелец карты",
    settings_card_phone: "Телефон",
    settings_save_success: "Данные профиля успешно сохранены!",
    settings_save_error: "Произошла ошибка при сохранении.",
    settings_notif_alert: "Будет активировано в ближайшее время.",
    settings_logout_alert: "Вышли из аккаунта.",

    // Manage Restaurant
    tab_orders: "Заказы",
    tab_categories: "Категории",
    tab_items: "Блюда",
    tab_settings: "Настройки",
    orders_active_only: "Активные заказы",
    orders_all: "Все заказы",
    orders_address: "Адрес доставки",
    orders_phone: "Телефон",
    orders_payment: "Способ оплаты",
    orders_items: "Состав заказа",
    orders_update_status: "Обновить статус",
    cats_title: "Список категорий",
    cats_new: "Новая категория",
    cats_add_btn: "Добавить",
    cats_name_placeholder: "Например: Пиццы",
    items_title: "Список блюд",
    items_new: "Новое Блюдо",
    items_edit: "Редактировать блюдо",
    items_name: "Название блюда",
    items_desc: "Описание блюда",
    items_price: "Цена (сум)",
    items_cat: "Категория",
    items_image: "Ссылка на изображение",
    items_upload_btn: "Загрузить фото",
    items_available: "В продаже?",
    items_saving: "Сохранение...",
    items_cancel: "Отмена",
    items_no_cat_warn: "Для добавления блюда сначала нужно создать категорию. Блюда отображаются только внутри категорий.",
    items_go_cat_btn: "Перейти к категориям",
    rest_settings_title: "Настройки ресторана",
    rest_name: "Название ресторана",
    rest_address: "Адрес",
    rest_delivery_fee: "Стоимость доставки (сум)",
    rest_min_order_form: "Минимальный заказ (сум)",
    rest_working_start: "Начало работы",
    rest_working_end: "Конец работы",
    rest_is_active: "Ресторан активен?",
    rest_branding_title: "Настройки брендинга",
    rest_logo_url: "Ссылка на логотип",
    rest_logo_upload: "Загрузить логотип",
    rest_theme: "Тема приложения",
    rest_accent: "Основной цвет"
  },
  en: {
    // Navigation
    nav_home: "Dashboard",
    nav_restaurants: "Restaurants",
    nav_settings: "Settings",

    // Dashboard
    dash_title: "Dashboard",
    dash_sub: "EcoRestaurant platform monitoring",
    dash_balance: "Balance",
    dash_my_account: "My Account",
    dash_top_up_btn: "Top Up Balance",
    dash_withdrawable: "Withdrawable funds",
    dash_withdraw_btn: "Withdraw",
    dash_active_orders: "Active orders",
    dash_received_orders: "Total orders",
    dash_total_revenue: "Total revenue",
    dash_sum: "UZS",
    dash_recent_orders: "Recent orders",
    dash_new_order: "New order received!",
    dash_customer: "Customer",
    dash_total: "Total",
    dash_status: "Status",
    dash_loading: "Loading...",
    dash_today: "Today",
    dash_preparing: "Preparing",
    dash_avg_check: "Average Check",
    dash_control: "Control",
    dash_stats: "Statistics",
    dash_add_menu: "Add to Menu",

    // Restaurants
    rest_title: "My Restaurants",
    rest_sub: "List of connected bots and restaurants",
    rest_add_btn: "New Restaurant",
    rest_modal_title: "Connect Bot via Token",
    rest_modal_name: "Restaurant Name",
    rest_modal_token: "Bot Token",
    rest_modal_create: "Create",
    rest_modal_cancel: "Cancel",
    rest_active: "Active",
    rest_inactive: "Inactive",
    rest_delivery: "Delivery",
    rest_min_order: "Min Order",
    rest_manage_btn: "Manage",
    rest_count_suffix: "restaurants",
    rest_empty_title: "You don't have any restaurants yet",
    rest_empty_btn: "Add your first restaurant",
    rest_online: "Online",
    rest_delete_warn: "For security reasons, deleting a restaurant can only be performed by the system administrator.",
    rest_orders_today: "orders today",
    rest_success_add: "Restaurant added successfully!",
    rest_error_add: "An error occurred. Check the bot token.",
    rest_modal_desc: "Enter bot and restaurant details",
    rest_modal_tip: "* A separate bot is recommended for each restaurant",
    rest_save_connect: "Save and Connect",
    rest_manage: "Manage",

    // Settings
    settings_title: "Settings",
    settings_sub: "Manage your account and payment settings",
    settings_profile_title: "Profile & Payment Details",
    settings_owner_name: "Full Name",
    settings_phone: "Phone Number",
    settings_card: "Card number for payouts (for orders)",
    settings_card_tip: "* Payouts/orders are recommended to be sent to this card",
    settings_save_btn: "Save",
    settings_saving: "Saving...",
    settings_language_title: "Language Settings",
    settings_help_center: "Help Center",
    settings_help_sub: "FAQ & technical support",
    settings_notifications: "Notifications",
    settings_notif_sub: "Push & sound settings",
    settings_logout: "Log Out",
    settings_card_holder: "Card Holder",
    settings_card_phone: "Phone",
    settings_save_success: "Profile details saved successfully!",
    settings_save_error: "Error occurred while saving.",
    settings_notif_alert: "Will be activated soon.",
    settings_logout_alert: "Logged out.",

    // Manage Restaurant
    tab_orders: "Orders",
    tab_categories: "Categories",
    tab_items: "Dishes",
    tab_settings: "Settings",
    orders_active_only: "Active orders",
    orders_all: "All orders",
    orders_address: "Delivery Address",
    orders_phone: "Phone",
    orders_payment: "Payment Type",
    orders_items: "Items Ordered",
    orders_update_status: "Update Status",
    cats_title: "Categories List",
    cats_new: "New Category",
    cats_add_btn: "Add",
    cats_name_placeholder: "e.g. Pizzas",
    items_title: "Dishes List",
    items_new: "New Dish",
    items_edit: "Edit Dish",
    items_name: "Dish name",
    items_desc: "Description",
    items_price: "Price (UZS)",
    items_cat: "Category",
    items_image: "Image URL",
    items_upload_btn: "Upload photo",
    items_available: "Available?",
    items_saving: "Saving...",
    items_cancel: "Cancel",
    items_no_cat_warn: "To add a dish, you must create a category first. Dishes are only displayed inside categories.",
    items_go_cat_btn: "Go to Categories",
    rest_settings_title: "Restaurant Settings",
    rest_name: "Restaurant Name",
    rest_address: "Address",
    rest_delivery_fee: "Delivery Fee (UZS)",
    rest_min_order_form: "Minimum Order (UZS)",
    rest_working_start: "Working Hours Start",
    rest_working_end: "Working Hours End",
    rest_is_active: "Is Restaurant Active?",
    rest_branding_title: "Branding Settings",
    rest_logo_url: "Logo URL",
    rest_logo_upload: "Upload Logo",
    rest_theme: "App Theme",
    rest_accent: "Accent Color"
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'uz',
  setLanguage: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    return (localStorage.getItem('language') as LanguageCode) || 'uz';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string) => {
    return translations[language]?.[key] || translations['uz']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
