"""Update_models_v2

Revision ID: 8200b326ccf3
Revises: bed93a0c55c5
Create Date: 2026-05-11 13:29:47.506725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8200b326ccf3'
down_revision: Union[str, Sequence[str], None] = 'bed93a0c55c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_categories_id'), table_name='menu_categories')
    op.drop_constraint(op.f('menu_categories_restaurant_id_fkey'), 'menu_categories', type_='foreignkey')
    op.create_foreign_key(None, 'menu_categories', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('menu_items', sa.Column('image_file_id', sa.String(), nullable=True))
    op.add_column('menu_items', sa.Column('is_available', sa.Boolean(), nullable=True))
    op.add_column('menu_items', sa.Column('sort_order', sa.Integer(), nullable=True))
    op.alter_column('menu_items', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_constraint(op.f('menu_items_restaurant_id_fkey'), 'menu_items', type_='foreignkey')
    op.drop_constraint(op.f('menu_items_category_id_fkey'), 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'menu_items', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('orders', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('location_lon', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_type', sa.Enum('cash', 'payme', 'click', 'uzum', 'paynet', name='paymenttype'), nullable=True))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.add_column('restaurant_owners', sa.Column('language', sa.Enum('uz', 'ru', 'en', name='userlanguage'), nullable=True))
    op.alter_column('restaurant_owners', 'balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
    op.add_column('restaurants', sa.Column('bot_id', sa.BigInteger(), nullable=True))
    op.add_column('restaurants', sa.Column('min_order', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('restaurants', sa.Column('working_start', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('working_end', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('restaurants', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('logo_file_id', sa.String(), nullable=True))
    op.alter_column('restaurants', 'delivery_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_restaurants_id'), table_name='restaurants')
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('transactions', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.add_column('users', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('language', sa.Enum('uz', 'ru', 'en', name='userlanguage'), nullable=True))
    op.create_foreign_key(None, 'users', 'restaurants', ['restaurant_id'], ['id'])
    op.add_column('withdrawals', sa.Column('note', sa.String(), nullable=True))
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_withdrawals_id'), table_name='withdrawals')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_withdrawals_id'), 'withdrawals', ['id'], unique=False)
    op.alter_column('withdrawals', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('withdrawals', 'note')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'language')
    op.drop_column('users', 'restaurant_id')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('transactions', 'created_at')
    op.create_index(op.f('ix_restaurants_id'), 'restaurants', ['id'], unique=False)
    op.alter_column('restaurants', 'delivery_fee',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('restaurants', 'logo_file_id')
    op.drop_column('restaurants', 'settings')
    op.drop_column('restaurants', 'is_active')
    op.drop_column('restaurants', 'working_end')
    op.drop_column('restaurants', 'working_start')
    op.drop_column('restaurants', 'min_order')
    op.drop_column('restaurants', 'bot_id')
    op.alter_column('restaurant_owners', 'balance',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('restaurant_owners', 'language')
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.alter_column('orders', 'total_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'payment_type')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'location_lon')
    op.drop_column('orders', 'location_lat')
    op.drop_column('orders', 'delivery_fee')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key(op.f('menu_items_category_id_fkey'), 'menu_items', 'menu_categories', ['category_id'], ['id'])
    op.create_foreign_key(op.f('menu_items_restaurant_id_fkey'), 'menu_items', 'restaurants', ['restaurant_id'], ['id'])
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.alter_column('menu_items', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('menu_items', 'sort_order')
    op.drop_column('menu_items', 'is_available')
    op.drop_column('menu_items', 'image_file_id')
    op.drop_constraint(None, 'menu_categories', type_='foreignkey')
    op.create_foreign_key(op.f('menu_categories_restaurant_id_fkey'), 'menu_categories', 'restaurants', ['restaurant_id'], ['id'])
    op.create_index(op.f('ix_menu_categories_id'), 'menu_categories', ['id'], unique=False)
    # ### end Alembic commands ###
